"""create users and pets tables

Revision ID: 277c267a3aed
Revises: 
Create Date: 2026-05-06 10:07:28.129122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277c267a3aed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False, comment='아이디 (4~20자)'),
    sa.Column('password', sa.String(), nullable=False, comment='해시된 비밀번호 (bcrypt)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='보호자 성명'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pets',
    sa.Column('pet_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='강아지 이름'),
    sa.Column('birth_year', sa.Integer(), nullable=True, comment='출생연도'),
    sa.Column('breed', sa.String(length=50), nullable=True, comment='견종'),
    sa.Column('weight', sa.Float(), nullable=True, comment='체중 kg (선택)'),
    sa.Column('medical_history', sa.Text(), nullable=True, comment='과거 병력 (선택)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pet_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('users')
    # ### end Alembic commands ###
