"""create notifications and push_subscriptions tables

Revision ID: 32c4246ca6db
Revises: bdefa95389ff
Create Date: 2026-05-09 01:48:23.088473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c4246ca6db'
down_revision: Union[str, Sequence[str], None] = 'bdefa95389ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False, comment='알림 타입 (analysis_complete 등)'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='알림 제목'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='읽음 여부'),
    sa.Column('related_type', sa.String(length=20), nullable=True, comment='관련 화면 종류 (analysis/pet/hospital)'),
    sa.Column('related_id', sa.BigInteger(), nullable=True, comment='관련 리소스 ID (클릭 시 이동)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('push_subscriptions',
    sa.Column('subscription_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False, comment='브라우저 푸시 엔드포인트 URL'),
    sa.Column('p256dh_key', sa.String(length=255), nullable=False, comment='암호화 공개키'),
    sa.Column('auth_key', sa.String(length=255), nullable=False, comment='인증키'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='디바이스 식별용 (선택)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id'),
    sa.UniqueConstraint('endpoint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_subscriptions')
    op.drop_table('notifications')
    # ### end Alembic commands ###
