"""create hospitals and favorite_hospitals tables

Revision ID: bdefa95389ff
Revises: eb81974f6cab
Create Date: 2026-05-08 06:10:11.031689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdefa95389ff'
down_revision: Union[str, Sequence[str], None] = 'eb81974f6cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('hospital_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='병원 이름'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='주소'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='위도'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='경도'),
    sa.Column('specialty', sa.String(length=50), nullable=True, comment='전문 분야 (자체 큐레이션)'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='병원 사진 URL'),
    sa.Column('business_hours', sa.JSON(), nullable=True, comment='요일별 영업시간 (JSON)'),
    sa.Column('certifications', sa.String(length=255), nullable=True, comment='인증 정보 (피어프리 등)'),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('favorite_hospitals',
    sa.Column('favorite_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.BigInteger(), nullable=False),
    sa.Column('hospital_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id'),
    sa.UniqueConstraint('pet_id', 'hospital_id', name='uniq_pet_hospital')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
