"""create analyses table

Revision ID: eb81974f6cab
Revises: fedbd555a1f8
Create Date: 2026-05-07 15:29:14.991722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb81974f6cab'
down_revision: Union[str, Sequence[str], None] = 'fedbd555a1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('analysis_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.BigInteger(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False, comment='업로드된 영상 URL'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/processing/completed/failed'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='normal/caution/danger'),
    sa.Column('ai_result', sa.JSON(), nullable=True, comment='AI 분석 요약 지표'),
    sa.Column('memo', sa.String(length=200), nullable=True, comment='사용자 메모 (0~200자, nullable)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='메모 수정 시 자동 갱신'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    # ### end Alembic commands ###
