"""update pets table - birth_date, gender, profile_image_url, enum

Revision ID: fedbd555a1f8
Revises: e418699afcf4
Create Date: 2026-05-07 15:08:16.599259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedbd555a1f8'
down_revision: Union[str, Sequence[str], None] = 'e418699afcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ============================================
    # Step 1: 새 컬럼 추가 (일단 nullable=True로!)
    # ============================================
    op.add_column('pets', sa.Column('birth_date', sa.Date(), nullable=True, comment='생년월일'))
    op.add_column('pets', sa.Column('gender', sa.String(length=10), nullable=True, comment='성별 (male/female)'))
    op.add_column('pets', sa.Column('profile_image_url', sa.String(length=255), nullable=True, comment='프로필 사진 경로 (nullable)'))

    # ============================================
    # Step 2: 기존 데이터 채우기 (NOT NULL 적용 전)
    # ============================================
    # birth_year를 birth_date로 변환 (1월 1일로 채움)
    op.execute("""
        UPDATE pets 
        SET birth_date = MAKE_DATE(birth_year, 1, 1) 
        WHERE birth_year IS NOT NULL
    """)
    
    # birth_year가 NULL인 경우 기본값 (혹시 모를 안전장치)
    op.execute("""
        UPDATE pets 
        SET birth_date = '2020-01-01' 
        WHERE birth_date IS NULL
    """)
    
    # gender 기본값 (기존 강아지는 일단 male로, 나중에 PUT API로 수정)
    op.execute("UPDATE pets SET gender = 'male' WHERE gender IS NULL")
    
    # medical_history NULL 또는 자유 입력값 → "없음"으로 통일
    op.execute("""
        UPDATE pets 
        SET medical_history = '없음' 
        WHERE medical_history IS NULL 
           OR medical_history NOT IN (
                '없음',
                '슬개골 탈구 이력 있음',
                '슬개골 수술 경험 있음',
                '관절 질환 (슬개골 외)',
                '근육/인대 부상 이력',
                '기타'
           )
    """)

    # ============================================
    # Step 3: NOT NULL 제약 적용 + 타입 변경 + 컬럼 삭제
    # ============================================
    op.alter_column('pets', 'birth_date', nullable=False)
    op.alter_column('pets', 'gender', nullable=False)
    
    op.alter_column('pets', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment='강아지 이름 (1~20자)',
               existing_comment='강아지 이름',
               existing_nullable=False)
    op.alter_column('pets', 'breed',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='견종 (16종 + 기타 enum)',
               existing_comment='견종')
    op.alter_column('pets', 'medical_history',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               comment='과거 병력 (6개 enum)',
               existing_comment='과거 병력 (선택)')
    
    op.drop_column('pets', 'birth_year')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=True, comment='출생연도'))
    op.alter_column('pets', 'medical_history',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               comment='과거 병력 (선택)',
               existing_comment='과거 병력 (6개 enum)')
    op.alter_column('pets', 'breed',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='견종',
               existing_comment='견종 (16종 + 기타 enum)')
    op.alter_column('pets', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment='강아지 이름',
               existing_comment='강아지 이름 (1~20자)',
               existing_nullable=False)
    op.drop_column('pets', 'profile_image_url')
    op.drop_column('pets', 'gender')
    op.drop_column('pets', 'birth_date')